### ISSUE TITLE
Compatibility with Julia 1.6

### ISSUE THREAD

**Issue by gdalle** [JuliaDecisionFocusedLearning/InferOpt.jl#26]
It would be nice to be compatible with Julia's Long Term Support (LTS) version 1.6.
I think the main obstacle at the moment is the use of the destructuring syntax `(; a, b) = x`, which was introduced in Julia 1.7. Shouldn't be hard to fix, and the test CI needs to be updated too.

**Comment by gdalle** [comment]
Use https://github.com/devmotion/SimpleUnPack.jl

**Comment by BatyLeo** [comment]
Is it really useful to be compatible with 1.6 ?

**Comment by gdalle** [comment]
> Is it really useful to be compatible with 1.6 ?

Debatable. The main reason is that it is the current LTS version, which means some careful companies might only want to use this one for fear of running into issues

**Comment by BatyLeo** [comment]
Julia v1.10 is the new LTS, and currently supported
